export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_ERROR = 'GET_CURRENCIES_ERROR';

export const GET_CONVERTIONS = 'GET_CONVERTIONS';
export const GET_CONVERTIONS_SUCCESS = 'GET_CONVERTIONS_SUCCESS';
export const GET_CONVERTIONS_ERROR = 'GET_CONVERTIONS_ERROR';